stages:
  - publish

publish-library:
  stage: publish
  image:
    name: docker.repo.tehik.ee/docker:stable
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  script:
    - |
      {
        echo "@tehik:registry=https://$ARTIFACTORY_NPM_API_URL"
        echo "//$ARTIFACTORY_NPM_API_URL:_authToken=$NPM_AUTH_TOKEN"
        echo "email=$NPM_AUTH_EMAIL"
      } | tee -a .npmrc
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
