stages:
  - test
  - build
  - publish

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

lint:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  stage: test
  needs: []
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint:ci
  interruptible: true

test:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  stage: test
  needs: []
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test
  interruptible: true

build:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  needs: []
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  interruptible: true

build-sb:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  needs: []
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build:sb
  interruptible: true

publish-library:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  when: manual
  stage: publish
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - |
      {
        echo "@tehik:registry=https://$ARTIFACTORY_NPM_API_URL"
        echo "//$ARTIFACTORY_NPM_API_URL:_authToken=$NPM_AUTH_TOKEN"
        echo "email=$NPM_AUTH_EMAIL"
      } | tee -a .npmrc
    - cp ./.npmrc ./dist
    - cd ./dist
    - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
