stages:
  - publish

default:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@tehik:registry=https://${CI_SERVER_HOST}/api/v4/packages/npm/"
        echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
        echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

publish-library:
  stage: publish
  script:
    - npm run build
    - cd ./dist/packages/components
    # - npm run semantic-release
    - npm publish
  #TODO - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
