stages:
  - test
  - build
  - publish

image:
  name: docker.repo.tehik.ee/node:lts-bullseye-slim
  pull_policy: if-not-present

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

lint:
  stage: test
  when: always
  interruptible: true
  script:
    - npm run lint:ci

test:
  stage: test
  when: always
  interruptible: true
  script:
    - npm run test

build:
  stage: build
  when: always
  interruptible: true
  script:
    - npm run build

build-sb:
  stage: build
  when: always
  interruptible: true
  script:
    - npm run build:sb

publish-library:
  when: manual
  stage: publish
  script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm run build
    - |
      {
        echo "@tehik:registry=https://$ARTIFACTORY_NPM_API_URL"
        echo "//$ARTIFACTORY_NPM_API_URL:_authToken=$NPM_AUTH_TOKEN"
        echo "email=$NPM_AUTH_EMAIL"
      } | tee -a .npmrc
    - HUSKY_SKIP_HOOKS=1 npm run semantic-release
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
