stages:
  - publish

default:
  image: docker.repo.tehik.ee/node:lts-bullseye-slim
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "//$ARTIFACTORY_NPM_API_URL:_authToken=$NPM_AUTH_TOKEN"
        echo "email=$NPM_AUTH_EMAIL"
      } | tee -a .npmrc
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

publish-library:
  stage: publish
  script:
    - npm run build
    - cp ./.npmrc ./dist/packages/components
    - cd ./dist/packages/components
    - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
