stages:
  - test
  - build
  - publish

image: docker.repo.tehik.ee/node:lts-bullseye-slim

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

lint:
  stage: test
  when: always
  interruptible: true
  script:
    - npm run lint:ci

test:
  stage: test
  when: always
  interruptible: true
  script:
    - npm run test

build:
  stage: build
  when: always
  interruptible: true
  script:
    - npm run build

build-sb:
  stage: build
  when: always
  interruptible: true
  script:
    - npm run build:sb

publish-library:
  when: manual
  stage: publish
  script:
    - npm run build
    - |
      {
        echo "@tehik:registry=https://$ARTIFACTORY_NPM_API_URL"
        echo "//$ARTIFACTORY_NPM_API_URL:_authToken=$NPM_AUTH_TOKEN"
        echo "email=$NPM_AUTH_EMAIL"
      } | tee -a .npmrc
    - cp ./.npmrc ./dist
    - cd ./dist
    - npm publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
