name: Deploy TEDI library storybook to GitHub pages

on:
  push:
    branches: ['master']

permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Use Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 'lts/*'
#      - name: Install dependencies
#        run: npm ci
#      - name: Build project
#        run: npm run build:sb
#      - name: Create Storybook artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: storybook-static
#          path: dist/storybook/components/
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    #needs: build
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      #- name: Deploy to GitHub Pages
        #uses: actions/deploy-pages@v4
        #with:
        #  artifact_name: storybook-static
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci # default: npm ci
          build_command: npm run build:sb # default: npm run build-storybook
          path: dist/storybook/components # default: dist/storybook
          checkout: true # default: true

